/**
 * Spam word database for cold email spam checking.
 * Comprehensive list of 400+ words/phrases that trigger spam filters,
 * categorized by type and severity.
 *
 * Sources: mailmeteor.com spam checker categories, industry spam filter databases,
 * and cold email deliverability best practices.
 */

export type SpamCategory =
  | 'money'
  | 'scam'
  | 'overpromise'
  | 'urgency'
  | 'health'
  | 'tech'
  | 'gambling';

export type SpamSeverity = 'high' | 'medium' | 'low';

export interface SpamWord {
  word: string;
  category: SpamCategory;
  severity: SpamSeverity;
}

export const SPAM_WORDS: SpamWord[] = [
  // ─── MONEY — HIGH SEVERITY ───────────────────────────────────────────
  { word: 'free', category: 'money', severity: 'high' },
  { word: 'cash', category: 'money', severity: 'high' },
  { word: 'money', category: 'money', severity: 'high' },
  { word: 'earn money', category: 'money', severity: 'high' },
  { word: 'make money', category: 'money', severity: 'high' },
  { word: 'extra cash', category: 'money', severity: 'high' },
  { word: 'extra income', category: 'money', severity: 'high' },
  { word: 'fast cash', category: 'money', severity: 'high' },
  { word: 'double your', category: 'money', severity: 'high' },
  { word: 'million dollars', category: 'money', severity: 'high' },
  { word: 'million', category: 'money', severity: 'high' },
  { word: 'billions', category: 'money', severity: 'high' },
  { word: 'cash bonus', category: 'money', severity: 'high' },
  { word: 'earn extra', category: 'money', severity: 'high' },
  { word: 'financial freedom', category: 'money', severity: 'high' },
  { word: 'get paid', category: 'money', severity: 'high' },
  { word: 'get rich', category: 'money', severity: 'high' },
  { word: 'income from home', category: 'money', severity: 'high' },
  { word: 'make money online', category: 'money', severity: 'high' },
  { word: 'money back', category: 'money', severity: 'high' },
  { word: 'money making', category: 'money', severity: 'high' },
  { word: 'no cost', category: 'money', severity: 'high' },
  { word: 'no fees', category: 'money', severity: 'high' },
  { word: 'no hidden costs', category: 'money', severity: 'high' },
  { word: 'risk free', category: 'money', severity: 'high' },
  { word: 'risk-free', category: 'money', severity: 'high' },
  { word: 'free access', category: 'money', severity: 'high' },
  { word: 'free consultation', category: 'money', severity: 'high' },
  { word: 'free gift', category: 'money', severity: 'high' },
  { word: 'free info', category: 'money', severity: 'high' },
  { word: 'free investment', category: 'money', severity: 'high' },
  { word: 'free leads', category: 'money', severity: 'high' },
  { word: 'free membership', category: 'money', severity: 'high' },
  { word: 'free money', category: 'money', severity: 'high' },
  { word: 'free offer', category: 'money', severity: 'high' },
  { word: 'free preview', category: 'money', severity: 'high' },
  { word: 'free quote', category: 'money', severity: 'high' },
  { word: 'free sample', category: 'money', severity: 'high' },
  { word: 'free trial', category: 'money', severity: 'high' },
  { word: 'giving away', category: 'money', severity: 'high' },

  // ─── MONEY — MEDIUM SEVERITY ─────────────────────────────────────────
  { word: 'affordable', category: 'money', severity: 'medium' },
  { word: 'bargain', category: 'money', severity: 'medium' },
  { word: 'bonus', category: 'money', severity: 'medium' },
  { word: 'budget', category: 'money', severity: 'medium' },
  { word: 'cheap', category: 'money', severity: 'medium' },
  { word: 'cost', category: 'money', severity: 'medium' },
  { word: 'credit', category: 'money', severity: 'medium' },
  { word: 'debt', category: 'money', severity: 'medium' },
  { word: 'discount', category: 'money', severity: 'medium' },
  { word: 'dollars', category: 'money', severity: 'medium' },
  { word: 'financing', category: 'money', severity: 'medium' },
  { word: 'fortune', category: 'money', severity: 'medium' },
  { word: 'income', category: 'money', severity: 'medium' },
  { word: 'investment', category: 'money', severity: 'medium' },
  { word: 'loan', category: 'money', severity: 'medium' },
  { word: 'lowest price', category: 'money', severity: 'medium' },
  { word: 'mortgage', category: 'money', severity: 'medium' },
  { word: 'offer', category: 'money', severity: 'medium' },
  { word: 'price', category: 'money', severity: 'medium' },
  { word: 'prices', category: 'money', severity: 'medium' },
  { word: 'profit', category: 'money', severity: 'medium' },
  { word: 'profits', category: 'money', severity: 'medium' },
  { word: 'promotion', category: 'money', severity: 'medium' },
  { word: 'refund', category: 'money', severity: 'medium' },
  { word: 'save big', category: 'money', severity: 'medium' },
  { word: 'save money', category: 'money', severity: 'medium' },
  { word: 'savings', category: 'money', severity: 'medium' },
  { word: 'sale', category: 'money', severity: 'medium' },

  // ─── MONEY — LOW SEVERITY ────────────────────────────────────────────
  { word: 'billing', category: 'money', severity: 'low' },
  { word: 'invoice', category: 'money', severity: 'low' },
  { word: 'payment', category: 'money', severity: 'low' },
  { word: 'pricing', category: 'money', severity: 'low' },
  { word: 'quote', category: 'money', severity: 'low' },
  { word: 'rates', category: 'money', severity: 'low' },
  { word: 'revenue', category: 'money', severity: 'low' },
  { word: 'roi', category: 'money', severity: 'low' },
  { word: 'value', category: 'money', severity: 'low' },
  { word: 'worth', category: 'money', severity: 'low' },

  // ─── SCAM — HIGH SEVERITY ────────────────────────────────────────────
  { word: 'act now', category: 'scam', severity: 'high' },
  { word: 'apply now', category: 'scam', severity: 'high' },
  { word: 'buy now', category: 'scam', severity: 'high' },
  { word: 'call now', category: 'scam', severity: 'high' },
  { word: 'click below', category: 'scam', severity: 'high' },
  { word: 'click here', category: 'scam', severity: 'high' },
  { word: 'click now', category: 'scam', severity: 'high' },
  { word: 'click this', category: 'scam', severity: 'high' },
  { word: 'congratulations', category: 'scam', severity: 'high' },
  { word: 'dear friend', category: 'scam', severity: 'high' },
  { word: 'dear sir', category: 'scam', severity: 'high' },
  { word: 'do it today', category: 'scam', severity: 'high' },
  { word: 'don\'t delete', category: 'scam', severity: 'high' },
  { word: 'don\'t hesitate', category: 'scam', severity: 'high' },
  { word: 'for free', category: 'scam', severity: 'high' },
  { word: 'for instant access', category: 'scam', severity: 'high' },
  { word: 'for you', category: 'scam', severity: 'high' },
  { word: 'great offer', category: 'scam', severity: 'high' },
  { word: 'hidden', category: 'scam', severity: 'high' },
  { word: 'hurry', category: 'scam', severity: 'high' },
  { word: 'information you requested', category: 'scam', severity: 'high' },
  { word: 'instant', category: 'scam', severity: 'high' },
  { word: 'limited time', category: 'scam', severity: 'high' },
  { word: 'no catch', category: 'scam', severity: 'high' },
  { word: 'no gimmick', category: 'scam', severity: 'high' },
  { word: 'no obligation', category: 'scam', severity: 'high' },
  { word: 'no purchase necessary', category: 'scam', severity: 'high' },
  { word: 'no questions asked', category: 'scam', severity: 'high' },
  { word: 'no strings attached', category: 'scam', severity: 'high' },
  { word: 'not spam', category: 'scam', severity: 'high' },
  { word: 'offer expires', category: 'scam', severity: 'high' },
  { word: 'once in a lifetime', category: 'scam', severity: 'high' },
  { word: 'open immediately', category: 'scam', severity: 'high' },
  { word: 'order now', category: 'scam', severity: 'high' },
  { word: 'please read', category: 'scam', severity: 'high' },
  { word: 'sign up free', category: 'scam', severity: 'high' },
  { word: 'special promotion', category: 'scam', severity: 'high' },
  { word: 'this isn\'t spam', category: 'scam', severity: 'high' },
  { word: 'urgent', category: 'scam', severity: 'high' },
  { word: 'what are you waiting for', category: 'scam', severity: 'high' },
  { word: 'while supplies last', category: 'scam', severity: 'high' },
  { word: 'winner', category: 'scam', severity: 'high' },
  { word: 'you have been selected', category: 'scam', severity: 'high' },
  { word: 'you\'re a winner', category: 'scam', severity: 'high' },

  // ─── SCAM — MEDIUM SEVERITY ──────────────────────────────────────────
  { word: 'acceptance', category: 'scam', severity: 'medium' },
  { word: 'access', category: 'scam', severity: 'medium' },
  { word: 'accordingly', category: 'scam', severity: 'medium' },
  { word: 'action required', category: 'scam', severity: 'medium' },
  { word: 'additional income', category: 'scam', severity: 'medium' },
  { word: 'as seen on', category: 'scam', severity: 'medium' },
  { word: 'auto email removal', category: 'scam', severity: 'medium' },
  { word: 'be your own boss', category: 'scam', severity: 'medium' },
  { word: 'beneficiary', category: 'scam', severity: 'medium' },
  { word: 'cancel anytime', category: 'scam', severity: 'medium' },
  { word: 'claim', category: 'scam', severity: 'medium' },
  { word: 'collect', category: 'scam', severity: 'medium' },
  { word: 'compare', category: 'scam', severity: 'medium' },
  { word: 'confidential', category: 'scam', severity: 'medium' },
  { word: 'confirmation', category: 'scam', severity: 'medium' },
  { word: 'deal', category: 'scam', severity: 'medium' },
  { word: 'direct email', category: 'scam', severity: 'medium' },
  { word: 'exclusive deal', category: 'scam', severity: 'medium' },
  { word: 'expire', category: 'scam', severity: 'medium' },
  { word: 'expires', category: 'scam', severity: 'medium' },
  { word: 'form', category: 'scam', severity: 'medium' },
  { word: 'gift card', category: 'scam', severity: 'medium' },
  { word: 'giving it away', category: 'scam', severity: 'medium' },
  { word: 'important information', category: 'scam', severity: 'medium' },
  { word: 'info you requested', category: 'scam', severity: 'medium' },
  { word: 'join millions', category: 'scam', severity: 'medium' },
  { word: 'lifetime', category: 'scam', severity: 'medium' },
  { word: 'limited', category: 'scam', severity: 'medium' },
  { word: 'luxury', category: 'scam', severity: 'medium' },
  { word: 'message from', category: 'scam', severity: 'medium' },
  { word: 'multi level marketing', category: 'scam', severity: 'medium' },
  { word: 'notspam', category: 'scam', severity: 'medium' },
  { word: 'obligation', category: 'scam', severity: 'medium' },
  { word: 'opt in', category: 'scam', severity: 'medium' },
  { word: 'per week', category: 'scam', severity: 'medium' },
  { word: 'potential earnings', category: 'scam', severity: 'medium' },
  { word: 'prize', category: 'scam', severity: 'medium' },
  { word: 'promise', category: 'scam', severity: 'medium' },
  { word: 'purchase', category: 'scam', severity: 'medium' },
  { word: 'remove', category: 'scam', severity: 'medium' },
  { word: 'reply remove', category: 'scam', severity: 'medium' },
  { word: 'request', category: 'scam', severity: 'medium' },
  { word: 'reversal', category: 'scam', severity: 'medium' },
  { word: 'sample', category: 'scam', severity: 'medium' },
  { word: 'satisfaction', category: 'scam', severity: 'medium' },
  { word: 'score', category: 'scam', severity: 'medium' },
  { word: 'selected', category: 'scam', severity: 'medium' },
  { word: 'sent in compliance', category: 'scam', severity: 'medium' },
  { word: 'sign up', category: 'scam', severity: 'medium' },
  { word: 'social security number', category: 'scam', severity: 'medium' },
  { word: 'subscribe', category: 'scam', severity: 'medium' },
  { word: 'supplies are limited', category: 'scam', severity: 'medium' },
  { word: 'take action', category: 'scam', severity: 'medium' },
  { word: 'terms and conditions', category: 'scam', severity: 'medium' },
  { word: 'trial', category: 'scam', severity: 'medium' },
  { word: 'undisclosed recipient', category: 'scam', severity: 'medium' },
  { word: 'unsolicited', category: 'scam', severity: 'medium' },
  { word: 'unsubscribe', category: 'scam', severity: 'medium' },
  { word: 'verify', category: 'scam', severity: 'medium' },
  { word: 'web traffic', category: 'scam', severity: 'medium' },
  { word: 'winning', category: 'scam', severity: 'medium' },
  { word: 'won', category: 'scam', severity: 'medium' },
  { word: 'work from home', category: 'scam', severity: 'medium' },

  // ─── SCAM — LOW SEVERITY ─────────────────────────────────────────────
  { word: 'click', category: 'scam', severity: 'low' },
  { word: 'here', category: 'scam', severity: 'low' },
  { word: 'link', category: 'scam', severity: 'low' },
  { word: 'now', category: 'scam', severity: 'low' },
  { word: 'open', category: 'scam', severity: 'low' },
  { word: 'opportunity', category: 'scam', severity: 'low' },
  { word: 'opt-in', category: 'scam', severity: 'low' },
  { word: 'sign-up', category: 'scam', severity: 'low' },

  // ─── OVERPROMISE — HIGH SEVERITY ──────────────────────────────────────
  { word: '100% free', category: 'overpromise', severity: 'high' },
  { word: '100% more', category: 'overpromise', severity: 'high' },
  { word: '100% satisfied', category: 'overpromise', severity: 'high' },
  { word: 'amazing', category: 'overpromise', severity: 'high' },
  { word: 'best price', category: 'overpromise', severity: 'high' },
  { word: 'fantastic deal', category: 'overpromise', severity: 'high' },
  { word: 'guarantee', category: 'overpromise', severity: 'high' },
  { word: 'guaranteed', category: 'overpromise', severity: 'high' },
  { word: 'incredible', category: 'overpromise', severity: 'high' },
  { word: 'it\'s effective', category: 'overpromise', severity: 'high' },
  { word: 'miracle', category: 'overpromise', severity: 'high' },
  { word: 'no risk', category: 'overpromise', severity: 'high' },
  { word: 'number one', category: 'overpromise', severity: 'high' },
  { word: 'one hundred percent', category: 'overpromise', severity: 'high' },
  { word: 'outstanding', category: 'overpromise', severity: 'high' },
  { word: 'promise you', category: 'overpromise', severity: 'high' },
  { word: 'risk-free', category: 'overpromise', severity: 'high' },
  { word: 'satisfaction guaranteed', category: 'overpromise', severity: 'high' },
  { word: 'the best', category: 'overpromise', severity: 'high' },
  { word: 'unbelievable', category: 'overpromise', severity: 'high' },
  { word: 'unlimited', category: 'overpromise', severity: 'high' },
  { word: 'wonderful', category: 'overpromise', severity: 'high' },

  // ─── OVERPROMISE — MEDIUM SEVERITY ────────────────────────────────────
  { word: 'act immediately', category: 'overpromise', severity: 'medium' },
  { word: 'all new', category: 'overpromise', severity: 'medium' },
  { word: 'best', category: 'overpromise', severity: 'medium' },
  { word: 'big', category: 'overpromise', severity: 'medium' },
  { word: 'blast', category: 'overpromise', severity: 'medium' },
  { word: 'breakthrough', category: 'overpromise', severity: 'medium' },
  { word: 'certified', category: 'overpromise', severity: 'medium' },
  { word: 'congratulations', category: 'overpromise', severity: 'medium' },
  { word: 'drastically', category: 'overpromise', severity: 'medium' },
  { word: 'effective', category: 'overpromise', severity: 'medium' },
  { word: 'elite', category: 'overpromise', severity: 'medium' },
  { word: 'endorsed', category: 'overpromise', severity: 'medium' },
  { word: 'enormous', category: 'overpromise', severity: 'medium' },
  { word: 'exclusive', category: 'overpromise', severity: 'medium' },
  { word: 'expert', category: 'overpromise', severity: 'medium' },
  { word: 'explode', category: 'overpromise', severity: 'medium' },
  { word: 'extraordinary', category: 'overpromise', severity: 'medium' },
  { word: 'fantastic', category: 'overpromise', severity: 'medium' },
  { word: 'guaranteed', category: 'overpromise', severity: 'medium' },
  { word: 'highest', category: 'overpromise', severity: 'medium' },
  { word: 'instantly', category: 'overpromise', severity: 'medium' },
  { word: 'lowest', category: 'overpromise', severity: 'medium' },
  { word: 'luxury', category: 'overpromise', severity: 'medium' },
  { word: 'mainstream', category: 'overpromise', severity: 'medium' },
  { word: 'massive', category: 'overpromise', severity: 'medium' },
  { word: 'once in a lifetime', category: 'overpromise', severity: 'medium' },
  { word: 'one time', category: 'overpromise', severity: 'medium' },
  { word: 'only', category: 'overpromise', severity: 'medium' },
  { word: 'phenomenal', category: 'overpromise', severity: 'medium' },
  { word: 'powerful', category: 'overpromise', severity: 'medium' },
  { word: 'proven', category: 'overpromise', severity: 'medium' },
  { word: 'real results', category: 'overpromise', severity: 'medium' },
  { word: 'remarkable', category: 'overpromise', severity: 'medium' },
  { word: 'results', category: 'overpromise', severity: 'medium' },
  { word: 'revolutionary', category: 'overpromise', severity: 'medium' },
  { word: 'secret', category: 'overpromise', severity: 'medium' },
  { word: 'shocking', category: 'overpromise', severity: 'medium' },
  { word: 'special', category: 'overpromise', severity: 'medium' },
  { word: 'superb', category: 'overpromise', severity: 'medium' },
  { word: 'superior', category: 'overpromise', severity: 'medium' },
  { word: 'ultimate', category: 'overpromise', severity: 'medium' },
  { word: 'unique', category: 'overpromise', severity: 'medium' },
  { word: 'unseen', category: 'overpromise', severity: 'medium' },

  // ─── OVERPROMISE — LOW SEVERITY ───────────────────────────────────────
  { word: 'boost', category: 'overpromise', severity: 'low' },
  { word: 'enhance', category: 'overpromise', severity: 'low' },
  { word: 'improve', category: 'overpromise', severity: 'low' },
  { word: 'increase', category: 'overpromise', severity: 'low' },
  { word: 'maximize', category: 'overpromise', severity: 'low' },
  { word: 'optimize', category: 'overpromise', severity: 'low' },
  { word: 'skyrocket', category: 'overpromise', severity: 'low' },
  { word: 'transform', category: 'overpromise', severity: 'low' },

  // ─── URGENCY — HIGH SEVERITY ──────────────────────────────────────────
  { word: 'act now', category: 'urgency', severity: 'high' },
  { word: 'apply immediately', category: 'urgency', severity: 'high' },
  { word: 'before it\'s too late', category: 'urgency', severity: 'high' },
  { word: 'buy today', category: 'urgency', severity: 'high' },
  { word: 'call free', category: 'urgency', severity: 'high' },
  { word: 'call today', category: 'urgency', severity: 'high' },
  { word: 'can\'t live without', category: 'urgency', severity: 'high' },
  { word: 'do it now', category: 'urgency', severity: 'high' },
  { word: 'don\'t miss out', category: 'urgency', severity: 'high' },
  { word: 'don\'t wait', category: 'urgency', severity: 'high' },
  { word: 'ending soon', category: 'urgency', severity: 'high' },
  { word: 'expires today', category: 'urgency', severity: 'high' },
  { word: 'final call', category: 'urgency', severity: 'high' },
  { word: 'for only', category: 'urgency', severity: 'high' },
  { word: 'get it now', category: 'urgency', severity: 'high' },
  { word: 'get started now', category: 'urgency', severity: 'high' },
  { word: 'hurry up', category: 'urgency', severity: 'high' },
  { word: 'immediately', category: 'urgency', severity: 'high' },
  { word: 'last chance', category: 'urgency', severity: 'high' },
  { word: 'limited offer', category: 'urgency', severity: 'high' },
  { word: 'limited time offer', category: 'urgency', severity: 'high' },
  { word: 'limited time only', category: 'urgency', severity: 'high' },
  { word: 'new customers only', category: 'urgency', severity: 'high' },
  { word: 'now only', category: 'urgency', severity: 'high' },
  { word: 'offer expires', category: 'urgency', severity: 'high' },
  { word: 'one time offer', category: 'urgency', severity: 'high' },
  { word: 'only today', category: 'urgency', severity: 'high' },
  { word: 'order today', category: 'urgency', severity: 'high' },
  { word: 'right now', category: 'urgency', severity: 'high' },
  { word: 'rush', category: 'urgency', severity: 'high' },
  { word: 'supplies running out', category: 'urgency', severity: 'high' },
  { word: 'time limited', category: 'urgency', severity: 'high' },
  { word: 'today only', category: 'urgency', severity: 'high' },
  { word: 'top urgent', category: 'urgency', severity: 'high' },
  { word: 'what are you waiting for', category: 'urgency', severity: 'high' },

  // ─── URGENCY — MEDIUM SEVERITY ────────────────────────────────────────
  { word: 'deadline', category: 'urgency', severity: 'medium' },
  { word: 'expiring', category: 'urgency', severity: 'medium' },
  { word: 'fast', category: 'urgency', severity: 'medium' },
  { word: 'final', category: 'urgency', severity: 'medium' },
  { word: 'hurry', category: 'urgency', severity: 'medium' },
  { word: 'instant', category: 'urgency', severity: 'medium' },
  { word: 'limited', category: 'urgency', severity: 'medium' },
  { word: 'new', category: 'urgency', severity: 'medium' },
  { word: 'quick', category: 'urgency', severity: 'medium' },
  { word: 'reminder', category: 'urgency', severity: 'medium' },
  { word: 'running out', category: 'urgency', severity: 'medium' },
  { word: 'soon', category: 'urgency', severity: 'medium' },
  { word: 'supply', category: 'urgency', severity: 'medium' },
  { word: 'time is running out', category: 'urgency', severity: 'medium' },
  { word: 'today', category: 'urgency', severity: 'medium' },
  { word: 'while stocks last', category: 'urgency', severity: 'medium' },

  // ─── URGENCY — LOW SEVERITY ───────────────────────────────────────────
  { word: 'alert', category: 'urgency', severity: 'low' },
  { word: 'asap', category: 'urgency', severity: 'low' },
  { word: 'critical', category: 'urgency', severity: 'low' },
  { word: 'important', category: 'urgency', severity: 'low' },
  { word: 'notice', category: 'urgency', severity: 'low' },
  { word: 'priority', category: 'urgency', severity: 'low' },
  { word: 'update', category: 'urgency', severity: 'low' },
  { word: 'warning', category: 'urgency', severity: 'low' },

  // ─── HEALTH — HIGH SEVERITY ───────────────────────────────────────────
  { word: 'cure', category: 'health', severity: 'high' },
  { word: 'cures', category: 'health', severity: 'high' },
  { word: 'diagnose', category: 'health', severity: 'high' },
  { word: 'diet', category: 'health', severity: 'high' },
  { word: 'lose weight', category: 'health', severity: 'high' },
  { word: 'medicine', category: 'health', severity: 'high' },
  { word: 'no medical', category: 'health', severity: 'high' },
  { word: 'pharmacy', category: 'health', severity: 'high' },
  { word: 'prescription', category: 'health', severity: 'high' },
  { word: 'supplement', category: 'health', severity: 'high' },
  { word: 'viagra', category: 'health', severity: 'high' },
  { word: 'weight loss', category: 'health', severity: 'high' },

  // ─── HEALTH — MEDIUM SEVERITY ─────────────────────────────────────────
  { word: 'anti-aging', category: 'health', severity: 'medium' },
  { word: 'body', category: 'health', severity: 'medium' },
  { word: 'cosmetic', category: 'health', severity: 'medium' },
  { word: 'fitness', category: 'health', severity: 'medium' },
  { word: 'health', category: 'health', severity: 'medium' },
  { word: 'healthy', category: 'health', severity: 'medium' },
  { word: 'herbal', category: 'health', severity: 'medium' },
  { word: 'medical', category: 'health', severity: 'medium' },
  { word: 'natural', category: 'health', severity: 'medium' },
  { word: 'organic', category: 'health', severity: 'medium' },
  { word: 'remedy', category: 'health', severity: 'medium' },
  { word: 'slim', category: 'health', severity: 'medium' },
  { word: 'treatment', category: 'health', severity: 'medium' },
  { word: 'wellness', category: 'health', severity: 'medium' },

  // ─── TECH — HIGH SEVERITY ─────────────────────────────────────────────
  { word: 'auto email removal', category: 'tech', severity: 'high' },
  { word: 'bulk email', category: 'tech', severity: 'high' },
  { word: 'click here', category: 'tech', severity: 'high' },
  { word: 'direct email', category: 'tech', severity: 'high' },
  { word: 'email harvest', category: 'tech', severity: 'high' },
  { word: 'email marketing', category: 'tech', severity: 'high' },
  { word: 'increase traffic', category: 'tech', severity: 'high' },
  { word: 'internet marketing', category: 'tech', severity: 'high' },
  { word: 'mass email', category: 'tech', severity: 'high' },
  { word: 'multi level marketing', category: 'tech', severity: 'high' },
  { word: 'online marketing', category: 'tech', severity: 'high' },
  { word: 'opt in', category: 'tech', severity: 'high' },
  { word: 'search engine', category: 'tech', severity: 'high' },
  { word: 'seo', category: 'tech', severity: 'high' },
  { word: 'social media marketing', category: 'tech', severity: 'high' },
  { word: 'spam', category: 'tech', severity: 'high' },
  { word: 'this is not spam', category: 'tech', severity: 'high' },
  { word: 'traffic', category: 'tech', severity: 'high' },
  { word: 'web traffic', category: 'tech', severity: 'high' },

  // ─── TECH — MEDIUM SEVERITY ───────────────────────────────────────────
  { word: 'ad', category: 'tech', severity: 'medium' },
  { word: 'ads', category: 'tech', severity: 'medium' },
  { word: 'advertising', category: 'tech', severity: 'medium' },
  { word: 'automated', category: 'tech', severity: 'medium' },
  { word: 'banner', category: 'tech', severity: 'medium' },
  { word: 'campaign', category: 'tech', severity: 'medium' },
  { word: 'digital marketing', category: 'tech', severity: 'medium' },
  { word: 'email blast', category: 'tech', severity: 'medium' },
  { word: 'follow up', category: 'tech', severity: 'medium' },
  { word: 'leads', category: 'tech', severity: 'medium' },
  { word: 'marketing', category: 'tech', severity: 'medium' },
  { word: 'newsletter', category: 'tech', severity: 'medium' },
  { word: 'online', category: 'tech', severity: 'medium' },
  { word: 'outreach', category: 'tech', severity: 'medium' },
  { word: 'software', category: 'tech', severity: 'medium' },
  { word: 'solution', category: 'tech', severity: 'medium' },
  { word: 'targeting', category: 'tech', severity: 'medium' },
  { word: 'tool', category: 'tech', severity: 'medium' },
  { word: 'website', category: 'tech', severity: 'medium' },

  // ─── TECH — LOW SEVERITY ──────────────────────────────────────────────
  { word: 'automate', category: 'tech', severity: 'low' },
  { word: 'automation', category: 'tech', severity: 'low' },
  { word: 'demo', category: 'tech', severity: 'low' },
  { word: 'integrate', category: 'tech', severity: 'low' },
  { word: 'integration', category: 'tech', severity: 'low' },
  { word: 'platform', category: 'tech', severity: 'low' },
  { word: 'saas', category: 'tech', severity: 'low' },
  { word: 'scale', category: 'tech', severity: 'low' },
  { word: 'startup', category: 'tech', severity: 'low' },
  { word: 'streamline', category: 'tech', severity: 'low' },

  // ─── GAMBLING — HIGH SEVERITY ─────────────────────────────────────────
  { word: 'bet', category: 'gambling', severity: 'high' },
  { word: 'betting', category: 'gambling', severity: 'high' },
  { word: 'casino', category: 'gambling', severity: 'high' },
  { word: 'gamble', category: 'gambling', severity: 'high' },
  { word: 'gambling', category: 'gambling', severity: 'high' },
  { word: 'jackpot', category: 'gambling', severity: 'high' },
  { word: 'lottery', category: 'gambling', severity: 'high' },
  { word: 'poker', category: 'gambling', severity: 'high' },
  { word: 'slot', category: 'gambling', severity: 'high' },
  { word: 'slots', category: 'gambling', severity: 'high' },
  { word: 'wager', category: 'gambling', severity: 'high' },

  // ─── GAMBLING — MEDIUM SEVERITY ───────────────────────────────────────
  { word: 'blackjack', category: 'gambling', severity: 'medium' },
  { word: 'odds', category: 'gambling', severity: 'medium' },
  { word: 'roulette', category: 'gambling', severity: 'medium' },
  { word: 'stakes', category: 'gambling', severity: 'medium' },
  { word: 'winnings', category: 'gambling', severity: 'medium' },
];
